# Generated by Django 6.0.5 on 2026-06-14 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='pending_provider',
            new_name='payment_provider',
        ),
    ]
